# Generated by Django 6.0.4 on 2026-05-09 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'permissions': [('can_view_article', 'Can view article'), ('can_create_article', 'Can create article'), ('can_update_article', 'Can update article'), ('can_delete_article', 'Can delete article')],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articles', models.ManyToManyField(to='NewsApp.article')),
            ],
            options={
                'permissions': [('can_view_newsletter', 'Can view newsletter'), ('can_create_newsletter', 'Can create newsletter'), ('can_update_newsletter', 'Can update newsletter'), ('can_delete_newsletter', 'Can delete newsletter')],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='NewsApp.publisher'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Editor', 'Editor'), ('Journalist', 'Journalist'), ('Reader', 'Reader')], default='Reader', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('published_newsletters', models.ManyToManyField(blank=True, related_name='journalist_authors', to='NewsApp.newsletter')),
                ('subscriptions_to_journalists', models.ManyToManyField(blank=True, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriptions_to_publishers', models.ManyToManyField(blank=True, related_name='subscribed_readers', to='NewsApp.publisher')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editor_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
