# Generated by Django 6.0.4 on 2026-05-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='published_newsletters',
        ),
    ]
